---
- name: SetupServer
  hosts: k8s_master
  become: yes

  tasks:
    - name: Add k8s folder
      ansible.builtin.file:
        path: /root/k8s
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy init config file to remote host
      ansible.builtin.copy:
        src: init_config.yaml
        dest: /root/k8s/init_config.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Add calico folder
      ansible.builtin.file:
        path: /root/k8s/calico
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Download calico tigera-operator
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/tigera-operator.yaml
        dest: /root/k8s/calico/tigera-operator.yaml
        mode: '0644'


    - name: Download calico custom-resources
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/custom-resources.yaml
        dest: /root/k8s/calico/custom-resources.yaml
        mode: '0644'

    - name: Download calico manifests
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/calico.yaml
        dest: /root/k8s/calico/calico.yaml
        mode: '0644'

    - name: Add metrics_server folder
      ansible.builtin.file:
        path: /root/k8s/metrics_server
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Download metrics server
      ansible.builtin.get_url:
        url: https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.2/components.yaml
        dest: /root/k8s/metrics_server/metrics-server.yaml
        mode: '0644'

    - name: Install kubernetes python package
      ansible.builtin.apt:
        name:
          - python3-kubernetes
        state: present

    - name: Kubeadm init
      ansible.builtin.shell: kubeadm init --config /root/k8s/init_config.yaml

    - name: Add .kube folder
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy admin.conf file in .kube on the remote machine
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes

    - name: Deploy calico tigera-operator.yaml
      kubernetes.core.k8s:
        state: present
        src: /root/k8s/calico/tigera-operator.yaml

    - name: Deploy calico custom-resources.yaml
      kubernetes.core.k8s:
        state: present
        src: /root/k8s/calico/custom-resources.yaml

    - name: Deploy calico.yaml
      kubernetes.core.k8s:
        state: present
        src: /root/k8s/calico/calico.yaml

    - name: Deploy metrics-server
      kubernetes.core.k8s:
        state: present
        src: /root/k8s/metrics_server/metrics-server.yaml

    - name: Gather list of CSRs
      kubernetes.core.k8s_info:
        api_version: certificates.k8s.io/v1
        kind: CertificateSigningRequest
      register: csr_list

    - name: Filter CSRs with pending status
      set_fact:
        csrs_pending: "{{ csr_list.resources | selectattr('status', 'equalto', {}) | list }}"

    - name: Approve pending CSRs
      shell: kubectl certificate approve {{ item.metadata.name }}
      loop: "{{ csrs_pending }}"
      when: csrs_pending | length > 0
      loop_control:
        label: "{{ item.metadata.name }}"